const REDIS_ATTEMPTS = 3;
const RETRY_CHECK = 20;
const MAX_DRAW_PER_REQUEST = 40;
const MAX_COMPUTE_UNIT_PER_REQUEST = 3000000;

const SPECIAL_PRIZE = "special";

export {
  REDIS_ATTEMPTS,
  RETRY_CHECK,
  MAX_DRAW_PER_REQUEST,
  MAX_COMPUTE_UNIT_PER_REQUEST,
  SPECIAL_PRIZE,
};
